version: "3.7"

services:
    web:
        build: nginx
        ports:
          - 80:80
          - 443:443
        depends_on:
          - api
        networks:
          - network

    api:
        build: domainchecker
        environment:
          - PORT=8080
        ports:
          - 8080:8080
        networks:
          - network
networks:
  network:
    driver: bridge
